feat: workflows depyloy

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -152,3 +152,75 @@ jobs:
             %0A💬 Message: <b>${{ github.event.head_commit.message }}</b>
             %0ACek disini: $CURRENT_REPO
             "
+
+---- script sebelumnya ---
+
+  deploy:
+    name: Deploy
+    runs-on: ubuntu-latest
+    needs: [laravel_build, laravel_test]
+    if: always()
+    env:
+      CURRENT_REPO: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
+      ID_RSA: ${{ secrets.ID_RSA }}
+      SERVER_USER: ${{ secrets.SERVER_USER }}
+      SERVER_IP: ${{ secrets.SERVER_IP }}
+      SSH_PORT: ${{ secrets.SSH_PORT }}
+
+    steps:
+      - name: Download artifact
+        uses: actions/download-artifact@v2
+        with:
+          name: build-artifact
+          path: .
+
+      - name: Check if artifact exists
+        run: ls -lh artifact.zip
+
+      - name: Send File to Telegram
+        run: |
+          if [ -f "artifact.zip" ]; then
+            curl --request POST ${{ secrets.TELEGRAM_DEPLOY }} \
+              --header 'Accept: */*' \
+              --form 'chat_id="${{ secrets.TELEGRAM_CHANNEL }}"' \
+              --form caption=$CURRENT_REPO \
+              --form document=@./artifact.zip
+          else
+            echo "Artifact file not found!"
+          fi
+
+      - name: Unzip artifact
+        run: unzip -o artifact.zip
+
+      - name: Add SSH key
+        run: |
+          echo "${{ secrets.ID_RSA }}" > ssh_private_key_cicd_polindra
+          chmod 600 ssh_private_key_cicd_polindra
+
+      - name: Delete artifact.zip on Server Cloud
+        run: ssh -i ssh_private_key_cicd_polindra -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP -p $SSH_PORT 'rm -f artifact.zip' || true
+
+      - name: Deploy to Server
+        run: |
+          echo "Deploying application..."
+          chmod og= ssh_private_key_cicd_polindra
+          rm -f -R .git && rm -f artifact.zip
+          zip -r artifact.zip .
+          rsync -avz --info=progress2 -e "ssh -i ssh_private_key_cicd_polindra -o StrictHostKeyChecking=no -p $SSH_PORT" artifact.zip $SERVER_USER@$SERVER_IP:/home/polindra
+
+      - name: Delete All file in Deploy Directory
+        run: |
+          ssh -i ssh_private_key_cicd_polindra -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP -p $SSH_PORT 'rm -rf /var/www/laravel/* || true && rm -rf /var/www/laravel/.* || true'
+
+      - name: Extract and Remove artifact.zip
+        run: ssh -i ssh_private_key_cicd_polindra -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP -p $SSH_PORT 'mkdir -p /var/www/laravel/ || true && unzip -qq -o artifact.zip -d /var/www/laravel/ || true && rm -f artifact.zip || true'
+
+      - name: Fill .env
+        run: ssh -i ssh_private_key_cicd_polindra -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP -p $SSH_PORT 'cd /var/www/laravel/ && echo "${{ secrets.ENV_FILE_CONTENT }}" > ".env"' || true
+
+      - name: Run migration in database server and give permission to storage
+        run: ssh -i ssh_private_key_cicd_polindra -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP -p $SSH_PORT 'cd /var/www/laravel/ && php artisan migrate --force && sudo chown polindra:www-data -R ./storage && chmod -R 775 ./storage'
+
+      - name: Delete SSH Key
+        run: rm -f ssh_private_key_cicd_polindra
+
